service: emptor-docs-processing

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - requirements/**
    - README.md
    - package.json
    - package-lock.json
    - requirements.txt

custom:
  pythonRequirements:
    dockerizePip: non-linux
    fileName: requirements/requirements-dev.txt

provider:
  name: aws
  runtime: python3.7
  region: eu-central-1

functions:
  create:
    handler: title/create.create
    events:
      - http:
          path: title
          method: post

