service: emptor-docs-processing

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: python3.7
  region: eu-central-1

functions:
  extract:
    handler: handler.extract_title
    events:
      - http:
          path: extract-title
          method: POST
